
name: Build Documentation in HTML

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

  workflow_dispatch:

concurrency:
  group: "html"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build Documentation with Sphinx
      id: pages
      shell: bash
      run: |
        cmake -S . -B build-doc -D BUILD_DOC_ONLY=yes
        cmake --build build-doc --target doc
